## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix function returns a list with different matrix functions 
## x is the input matrix corresponding to which makeCachematrix creates a list
## with different matrix basic functions
makeCacheMatrix <- function(x = matrix()) { ## by default x is 1x 1 matrix
    #Initialize inverse equals to NULL
    m<- NULL
    # Set function is useful when we want to override the vale of x in already
    # created makecache matrix
    set<- function(y) {
        #cache the matrix so that if successive operation are called on the same data
        # it can use teh cached value of x
        x <<- y
        #remove the previous stored (if any) inverse from the cache by replacing the old value
        m <<- NULL
    }
    # return the actual matrix
    get<- function() x
    # set the solution value in the cache
    setsolution <- function(sol) m <<- sol
    # return the solution, also used to check whether solution was already present in the cache or not
    getsolution <- function() m
    # return type of function
    # each element of the list is a function
    list(set = set, get=get, setsolution=setsolution, getsolution=getsolution)
}



# cacheSolve function Computes  the inverse of an object generated by makeCacheMatrix
# used the cached value(if already computed) to find the inverse of the object generated by
# makeCacheMatrix

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    m<-x$getsolution()
    # check whether inverse is already computed(present in cache) or not
    if(!is.null(m))
    {
        # inverse has alread computed in the past and it is present in the cache
        message("getting cached data")
        # return the inverse of teh matrix
        return(m)
    }
    #Contol will come at this point if input is new(inverse is not computed in past)
    #get the actual matrix in data object
    data <- x$get()
    # find the inverse of the matrix data and store the output in m
    m<- solve(data)
    #store the inverse in the cache for successive use
    x$setsolution(m)
    # return the inverse of the matrix
    m
}
